[build]
dockerfile = "Dockerfile"

[deploy]
healthcheckPath    = "/api/test/status"
healthcheckTimeout = 10
restartPolicyType  = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "server-bench"
